"""initial schema

Revision ID: f73869c5de17
Revises: 
Create Date: 2026-07-08 17:14:19.765577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f73869c5de17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host', 'password', name='uq_router_host_password')
    )
    op.create_table('whitelist',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mac', sa.String(), nullable=False),
    sa.Column('wol', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('router_id', 'name', name='uq_device_router_name')
    )
    op.create_table('user_routers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('router_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'router_id')
    )
    op.create_table('user_state',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_router_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_state')
    op.drop_table('user_routers')
    op.drop_table('devices')
    op.drop_table('whitelist')
    op.drop_table('routers')
    # ### end Alembic commands ###
